spring:
  application:
    name: maut-core-backend
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/maut_core
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    # Set to none to prevent JPA from trying to create or validate schema
    # We'll rely on Flyway for schema creation
    hibernate:
      ddl-auto: none
    show-sql: true
    # Remove the defer-datasource-initialization to avoid circular dependency
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration,classpath:db/modules/hello,classpath:db/modules/clientapplication,classpath:db/modules/authenticator,classpath:db/modules/transaction,classpath:db/modules/activity

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  
logging:
  level:
    org.springframework: INFO
    com.maut.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
