# The name of this app. Must be unique within a project.
name: core

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Java documentation
# (https://docs.platform.sh/languages/java.html#supported-versions)
# to find the supported versions for the 'java' type.
type: 'java:21'

disk: 1024 # Adjust as needed

hooks:
  build: |
    set -e
    echo "--- DEBUG: Current directory is $(pwd) ---"
    echo "--- DEBUG: Listing /app contents ---"
    ls -la /app
    echo "--- DEBUG: Attempting Maven build from /app, assuming pom.xml is at /app/pom.xml ---"
    mvn -f /app/pom.xml clean package -DskipTests
    echo "--- DEBUG: Maven build finished. Listing target directory /app/target ---"
    ls -la /app/target || true # List target, don't fail if not there (though it should be)

# The web section configures how your application is exposed to the web.
web:
  commands:
    start: |
      java -jar target/maut-core-backend-0.0.1-SNAPSHOT.jar --server.port=$PORT

relationships:
  database: "core-db:postgresql"